# Generated by Django 5.1.5 on 2025-01-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbi_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_Name', models.CharField(max_length=30)),
                ('admin_Contact', models.CharField(max_length=30)),
                ('admin_Email', models.CharField(max_length=30)),
                ('admin_Password', models.CharField(max_length=30)),
            ],
        ),
    ]
