# Generated by Django 5.1.5 on 2025-01-18 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbi_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_district',
            old_name='distrcit_name',
            new_name='district_name',
        ),
    ]
