# Generated by Django 5.1.5 on 2025-02-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_rename_distrcit_name_tbl_district_district_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmin_district', models.CharField(max_length=30)),
                ('Admin_place', models.CharField(max_length=30)),
            ],
        ),
    ]
