# Generated by Django 5.1.5 on 2025-03-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_email', models.CharField(max_length=30)),
                ('employee_contact', models.CharField(max_length=30)),
                ('employee_password', models.CharField(max_length=30)),
                ('employee_experience', models.CharField(max_length=30)),
            ],
        ),
    ]
