# Generated by Django 5.1.5 on 2025-03-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_id', models.CharField(max_length=30)),
                ('mentor_name', models.CharField(max_length=30)),
                ('mentor_email', models.CharField(max_length=30)),
                ('mentor_password', models.CharField(max_length=30)),
                ('mentor_experience', models.CharField(max_length=30)),
                ('mentor_jobTitle', models.CharField(max_length=30)),
                ('mentor_status', models.CharField(max_length=30)),
                ('mentor_photo', models.FileField(upload_to='Assets/Files/Mentor')),
            ],
        ),
    ]
