# Generated by Django 5.1.5 on 2025-03-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_mentor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_community',
        ),
    ]
