# Generated by Django 5.1.5 on 2025-03-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_delete_tbl_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=30)),
                ('community_discription', models.CharField(max_length=30)),
                ('community_Date', models.DateField(auto_now_add=True)),
                ('community_status', models.CharField(max_length=30)),
            ],
        ),
    ]
