# Generated by Django 5.1.5 on 2025-03-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_community'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_employees',
        ),
    ]
