# Generated by Django 5.1.5 on 2025-03-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_delete_tbl_employees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_mentor',
        ),
    ]
