# Generated by Django 5.1.5 on 2025-03-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_community_mentor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_community_mentor',
        ),
    ]
