# Generated by Django 5.1.5 on 2025-03-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_alter_tbl_community_community_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_mentor',
            name='mentor_status',
            field=models.IntegerField(default=0),
        ),
    ]
