# Generated by Django 5.1.5 on 2025-03-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_alter_tbl_mentor_mentor_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_community_mentor',
        ),
        migrations.DeleteModel(
            name='tbl_mentor',
        ),
    ]
