# Generated by Django 5.1.5 on 2025-03-29 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_delete_tbl_community_mentor_delete_tbl_mentor'),
        ('Guest', '0003_tbl_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_community_mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_mentor_status', models.IntegerField(default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_community')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_mentor')),
            ],
        ),
    ]
