# Generated by Django 5.1.5 on 2025-03-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='place',
        ),
    ]
