# Generated by Django 5.1.5 on 2025-03-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_remove_tbl_user_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=30)),
                ('mentor_email', models.CharField(max_length=30)),
                ('mentor_password', models.CharField(max_length=30)),
                ('mentor_experience', models.CharField(max_length=30)),
                ('mentor_jobTitle', models.CharField(max_length=30)),
                ('mentor_status', models.IntegerField(default=0)),
                ('mentor_photo', models.FileField(upload_to='Assets/Files/Mentor')),
            ],
        ),
    ]
