# Generated by Django 5.1.5 on 2025-02-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_tbl_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
