# Generated by Django 5.1.5 on 2025-03-21 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_tbl_lobby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_lobby',
        ),
    ]
