# Generated by Django 5.1.5 on 2025-04-23 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_mentor'),
        ('User', '0017_tbl_communitychat'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_dm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm_message', models.CharField(max_length=30)),
                ('dm_status', models.IntegerField(default=0)),
                ('dm_date_time', models.DateTimeField(auto_now_add=True)),
                ('dm_photo', models.FileField(upload_to='ChatFiels/')),
                ('dm_files', models.FileField(upload_to='ChatFiels/')),
                ('dm_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_from', to='Guest.tbl_user')),
                ('dm_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_to', to='Guest.tbl_user')),
            ],
        ),
    ]
