# Generated by Django 5.2 on 2025-04-23 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_mentor'),
        ('User', '0019_tbl_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_notification',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='Guest.tbl_user'),
        ),
        migrations.AlterField(
            model_name='tbl_notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Guest.tbl_user'),
        ),
        migrations.CreateModel(
            name='tbl_friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends1', to='Guest.tbl_user')),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends2', to='Guest.tbl_user')),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
