# Generated by Django 5.1.5 on 2025-04-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_tbl_notification_from_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_dm',
        ),
    ]
