# Generated by Django 5.1.5 on 2025-04-23 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_mentor'),
        ('User', '0021_delete_tbl_dm'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_dm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fromd', to='Guest.tbl_user')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tod', to='Guest.tbl_user')),
            ],
        ),
    ]
