# Generated by Django 5.2 on 2025-04-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_tbl_dm'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_friend',
            name='friend_status',
            field=models.IntegerField(default=0),
        ),
    ]
