# Generated by Django 5.1.5 on 2025-04-23 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_mentor'),
        ('User', '0023_tbl_friend_friend_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbl_friend',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tbl_communitychat',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_mentor'),
        ),
    ]
